version: 2
jobs:
  build:
    working_directory: ~/klaybot
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle" }}
      - run: chmod +x gradlew
      - run: ./gradlew assemble
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle" }}
      - store_artifacts:
          path: build/libs
  deploy:
    working_directory: ~/klaybot
    machine:
      enabled: true
    steps:
      - run:
          name: Archive existing jars
          command: ssh $SSH_USER@$SSH_HOST "sudo mv $KLAYBOT_HOME/*.jar $KLAYBOT_HOME/archive/"
      - run:
          name: Copy artifact to host
          command: scp build/libs/*.jar "$SSH_USER@$SSH_HOST:/home/$SSH_USER/"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
#          filters:
#            branches:
#              only: master
