version: 2.1

jobs:
  build:
    working_directory: /tmp/klaybot
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle" }}
      - run: chmod +x gradlew
      - run: ./gradlew assemble
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle" }}

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
